In [2]:
import pandas as pd

In [47]:
df = pd.read_csv('data/python_data_analytics_ecommerce_simulated_dates.csv')

In [48]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerType,Region,State,Product,Category,Quantity,UnitPrice,Discount,SalesChannel,PaymentMethod,ShippingMethod,Returned,CustomerRating
0,ORD-110092,2/19/2025,CUST-1600,Returning,West,CA,Wireless Mouse,Electronics,2,36.48,0.00,Retail Store,Apple Pay,2-Day,No,3.0
1,ORD-102705,3/6/2026,CUST-6641,Returning,Northeast,CT,USB-C Hub,Electronics,1,41.12,0.10,Online,Apple Pay,Next Day,No,NaN
2,ORD-103027,12/30/2025,CUST-2542,New,Southeast,NC,Jacket,Clothing,1,122.56,0.15,Online,Bank Transfer,Express,No,3.0
3,ORD-102280,2/3/2026,CUST-6731,New,West,AZ,Foam Roller,Fitness,1,26.55,0.00,Marketplace,Credit Card,Express,No,5.0
4,ORD-103454,9/1/2025,CUST-3695,Returning,West,AZ,Smart Watch,Electronics,1,151.36,0.15,Retail Store,Credit Card,Standard,No,3.0

In [49]:
df.shape

(12500, 16)

In [50]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerType', 'Region', 'State',
       'Product', 'Category', 'Quantity', 'UnitPrice', 'Discount',
       'SalesChannel', 'PaymentMethod', 'ShippingMethod', 'Returned',
       'CustomerRating'],
      dtype='str')

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         12500 non-null  str
 1   OrderDate       12475 non-null  str
 2   CustomerID      12500 non-null  str
 3   CustomerType    12372 non-null  str
 4   Region          12453 non-null  str
 5   State           12500 non-null  str
 6   Product         12500 non-null  str
 7   Category        12405 non-null  str
 8   Quantity        12500 non-null  int64
 9   UnitPrice       12500 non-null  str
 10  Discount        12500 non-null  float64
 11  SalesChannel    12500 non-null  str
 12  PaymentMethod   12500 non-null  str
 13  ShippingMethod  12412 non-null  str
 14  Returned        12500 non-null  str
 15  CustomerRating  11241 non-null  float64
dtypes: float64(2), int64(1), str(13)
memory usage: 1.5 MB

In [52]:
df.isnull().sum()

OrderID              0
OrderDate           25
CustomerID           0
CustomerType       128
Region              47
State                0
Product              0
Category            95
Quantity             0
UnitPrice            0
Discount             0
SalesChannel         0
PaymentMethod        0
ShippingMethod      88
Returned             0
CustomerRating    1259
dtype: int64

In [53]:
df.duplicated().sum()

np.int64(37)

In [54]:
df[df.duplicated()].head()

,OrderID,OrderDate,CustomerID,CustomerType,Region,State,Product,Category,Quantity,UnitPrice,Discount,SalesChannel,PaymentMethod,ShippingMethod,Returned,CustomerRating
1036,ORD-102387,9/3/2025,CUST-4725,New,Southeast,GA,Notebook Set,Home & Office,4,18.16,0.05,Online,PayPal,Express,No,3.0
2348,ORD-103090,6/6/2026,CUST-2623,New,Southwest,OK,USB-C Hub,Electronics,1,39.76,0.00,Online,Bank Transfer,2-Day,No,3.0
4675,ORD-111034,5/6/2025,CUST-1276,VIP,West,NV,Wireless Headphones,ELECTRONICS,2,92.02,0.10,Retail Store,Apple Pay,Standard,No,4.0
5215,ORD-103148,7/9/2026,CUST-2041,Returning,Northeast,CT,Jacket,Clothing,3,126.14,0.05,Corporate,Bank Transfer,2-Day,No,5.0
5382,ORD-109272,3/1/2025,CUST-2382,Returning,midwest,MI,Wireless Headphones,Electronics,1,92.96,0.00,Online,Debit Card,Express,No,5.0

In [56]:
df = df.drop_duplicates()

In [57]:
df.shape

(12463, 16)

In [58]:
df.duplicated().sum()

np.int64(0)

In [59]:
df['Category'].value_counts(dropna=False)

Category
Electronics      3989
Home & Office    2940
Clothing         2704
Fitness          2097
ELECTRONICS       117
electronics       107
NaN                95
home & office      92
HOME & OFFICE      86
clothing           79
FITNESS            54
CLOTHING           52
fitness            51
Name: count, dtype: int64

In [60]:
df['Category'] = df['Category'].str.strip().str.title()

In [61]:
df['Category'].value_counts(dropna=False)

Category
Electronics      4213
Home & Office    3118
Clothing         2835
Fitness          2202
NaN                95
Name: count, dtype: int64

In [62]:
df['CustomerType'] = df['CustomerType'].str.strip().str.title()

In [64]:
df['Region'].value_counts(dropna=False)

Region
West         2733
Midwest      2522
Southeast    2404
Southwest    2139
Northeast    2135
west           70
WEST           57
midwest        51
MIDWEST        51
NORTHEAST      49
southeast      46
NaN            46
SOUTHEAST      43
southwest      43
SOUTHWEST      40
northeast      34
Name: count, dtype: int64

In [65]:
df['Region'] = df['Region'].str.strip().str.title()

In [66]:
df['Region'].value_counts(dropna=False)

Region
West         2860
Midwest      2624
Southeast    2493
Southwest    2222
Northeast    2218
NaN            46
Name: count, dtype: int64

In [72]:
df['UnitPrice'].head(20)

0       36.48
1       41.12
2      122.56
3       26.55
4      151.36
5      346.78
6       47.84
7      120.82
8      180.22
9      133.55
10     150.59
11    $326.38
12      46.03
13      84.75
14      80.78
15      35.47
16      34.11
17       18.9
18     143.09
19      66.77
Name: UnitPrice, dtype: str

In [73]:
df['UnitPrice'] = (
    df['UnitPrice']
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
)

df['UnitPrice'] = pd.to_numeric(df['UnitPrice'], errors='coerce')

In [74]:
df['UnitPrice'].dtype

dtype('float64')

In [75]:
df['OrderDate'] = pd.to_datetime(
    df['OrderDate'], format='mixed', errors='coerce'
)

In [76]:
df['OrderDate'].head()

0   2025-02-19
1   2026-03-06
2   2025-12-30
3   2026-02-03
4   2025-09-01
Name: OrderDate, dtype: datetime64[us]

In [77]:
df['OrderDate'].isnull().sum()

np.int64(25)

In [78]:
df['Category'] = df['Category'].fillna('Unknown')
df['Region'] = df['Region'].fillna('Unknown')
df['CustomerType'] = df['CustomerType'].fillna('Unknown')
df['ShippingMethod'] = df['ShippingMethod'].fillna('Unknown')

In [79]:
df['GrossRevenue'] = df['Quantity'] * df['UnitPrice']

In [80]:
df['Revenue'] = (
    df['Quantity'] * df['UnitPrice'] * (1-df['Discount'])
)

In [81]:
df['Revenue'] = df['Revenue'].round(2)

In [85]:
df[
    ['Quantity', 'UnitPrice', 'Discount', 'Revenue', 'CustomerRating']
].describe()

           Quantity     UnitPrice      Discount       Revenue  CustomerRating
count  12463.000000  12463.000000  12463.000000  12463.000000    11208.000000
mean       1.878119     80.379360      0.054971    142.205523        4.029265
std        1.082308     69.113349      0.061741    164.173351        1.032375
min        1.000000     17.480000      0.000000     14.250000        1.000000
25%        1.000000     34.655000      0.000000     48.240000        4.000000
50%        2.000000     60.260000      0.050000     86.500000        4.000000
75%        2.000000     95.110000      0.100000    171.340000        5.000000
max        5.000000    356.390000      0.200000   1759.000000        5.000000

In [92]:
total_revenue = df['Revenue'].sum()

print(f'Total Revenue: ${total_revenue:,.2f}')

Total Revenue: $1,772,307.43

In [89]:
total_orders = df['OrderID'].nunique()

print(f'Total Order: {total_orders:,}')

Total Order: 12,350

In [91]:
total_customers = df['CustomerID'].nunique()

print(f'Total Customers: {total_customers:,}')

Total Customers: 5,115

In [93]:
average_order_value = total_revenue / total_orders

print(f'Average Order Value: ${average_order_value:,.2f}')

Average Order Value: $143.51

In [94]:
revenue_by_product = (
    df.groupby('Product')['Revenue'].sum().sort_values(ascending=False)
)

revenue_by_product.head(10)

Product
Standing Desk          312630.17
Smart Watch            183424.12
Office Chair           182465.32
Mechanical Keyboard    118177.37
Wireless Headphones    116647.49
Jacket                 106505.03
Dumbbell Set            87805.62
Bluetooth Speaker       82258.81
Running Shoes           64911.34
Jeans                   59459.51
Name: Revenue, dtype: float64

In [95]:
top_5_product = revenue_by_product.head(5)
top_5_product

Product
Standing Desk          312630.17
Smart Watch            183424.12
Office Chair           182465.32
Mechanical Keyboard    118177.37
Wireless Headphones    116647.49
Name: Revenue, dtype: float64

In [96]:
revenue_by_region = (
    df.groupby('Region')['Revenue'].sum().sort_values(ascending=False)
)

revenue_by_region.head(10)

Region
West         397274.73
Midwest      377186.56
Southeast    351575.06
Southwest    324570.42
Northeast    316885.82
Unknown        4814.84
Name: Revenue, dtype: float64

In [97]:
customer_type_revenue = (
    df.groupby('CustomerType')['Revenue'].sum().sort_values(ascending=False)
)

customer_type_revenue

CustomerType
Returning    993778.57
New          580777.33
Vip          178147.78
Unknown       19603.75
Name: Revenue, dtype: float64

In [99]:
customer_type_summary = (
    df.groupby('CustomerType').agg(
        TotalRevenue=('Revenue', 'sum'),
        Orders=('OrderID', 'nunique'),
        AvgOrderValue=('Revenue', 'mean')
    ).sort_values('TotalRevenue', ascending=False)
)

customer_type_summary

              TotalRevenue  Orders  AvgOrderValue
CustomerType
Returning        993778.57    6883     143.340339
New              580777.33    4085     140.658109
Vip              178147.78    1256     139.943268
Unknown           19603.75     126     153.154297

In [100]:
channel_summary = (
    df.groupby('SalesChannel')['Revenue']
    .sum()
    .sort_values(ascending=False)
)

channel_summary

SalesChannel
Online          825915.28
Retail Store    470841.96
Marketplace     312276.92
Corporate       163273.27
Name: Revenue, dtype: float64

In [101]:
return_summary = (
    df.groupby('Returned').agg(
        Orders=('OrderID', 'nunique'),
        Revenue=('Revenue', 'sum')
    )
)

return_summary

          Orders     Revenue
Returned
No         11350  1635248.86
Yes         1000   137058.57

In [102]:
df['Month'] = df['OrderDate'].dt.to_period('M')

monthly_revenue = (
    df.groupby('Month')['Revenue'].sum()
)

monthly_revenue.head()

Month
2025-01     95161.09
2025-02    105440.12
2025-03    106187.36
2025-04     91059.69
2025-05    108188.21
Freq: M, Name: Revenue, dtype: float64

In [103]:
print('TOP 5 PRODUCTS')
print(top_5_product)

print('\nREVENUE BY REGION')
print(revenue_by_region)

print('\nCUSTOMER TYPE SUMMARY')
print(customer_type_summary)

TOP 5 PRODUCTS
Product
Standing Desk          312630.17
Smart Watch            183424.12
Office Chair           182465.32
Mechanical Keyboard    118177.37
Wireless Headphones    116647.49
Name: Revenue, dtype: float64

REVENUE BY REGION
Region
West         397274.73
Midwest      377186.56
Southeast    351575.06
Southwest    324570.42
Northeast    316885.82
Unknown        4814.84
Name: Revenue, dtype: float64

CUSTOMER TYPE SUMMARY
              TotalRevenue  Orders  AvgOrderValue
CustomerType
Returning        993778.57    6883     143.340339
New              580777.33    4085     140.658109
Vip              178147.78    1256     139.943268
Unknown           19603.75     126     153.154297

In [104]:
df.to_csv('data/python_data_analytics_cleaned.csv', index=False)